/**
 * Fixed collection of `FieldSkillName`s.
 */
const FieldSkills = [
    'Forestry',
    'Light Mastery',
    'Fire Mastery',
    'Earth Mastery',
    'Dark Mastery',
    'Wind Mastery',
    'Ice Mastery',
    'Water Mastery',
    'Electric Mastery',
    'Fire Mastery',
    'Focus',
    'Girls\' Talk',
    'Expeditionist',
    'Ichthyology',
    'Mineralogy',
    'Lockpicking',
    'Transport Mastery',
    'Keen Eye',
    'Production Mastery',
    'Entomology',
    'Botany',
    'Salvaging Mastery',
    'Ancient Wisdom',
    'Chivalry',
    'Beguiling Charm',
    'Fortitude',
    'Leaping',
    'Nopon Wisdom',
    'Superstrength',
    'Passionate Soul',
    'Kind Soul',
    'Justice-Loving Soul',
    'Miasma Dispersal',
    'Info Collector',
    'Industry Mastery',
    'Cooking',
    'Assassination',
    'Patissier',
    'Cavalier Attitude',
    'Fleet of Foot',
    'One Lucky Gal',
    'Clairvoyant Eye',
    'Titan Weapon Wisdom',
    'Phonex Linguistics',
    'Dumpling Pro',
    'Extra-Ancient Wisdom',
    'Mastery of Thunder',
    'Birdbrain',
    'Mental Arithmetic',
    'Rampage',
    'Weaving',
    'Prospecting',
    'Icecraft',
    'Eye for Beauty',
    'Ardent Cooking'
] as const;

export default FieldSkills;
